-- DROP TABLE IF EXISTS T_ALARM_CONFIG;

CREATE TABLE IF NOT EXISTS T_ALARM_CONFIG
(
    ID            IDENTITY     NOT NULL COMMENT '主键ID',
    URL           VARCHAR(200) NOT NULL DEFAULT '' COMMENT '钉钉告警的url',
    SECRET        VARCHAR(100)          DEFAULT '' COMMENT '钉钉机器人加签',
    KEYS          VARCHAR(200) NOT NULL DEFAULT '' COMMENT '告警关键字',
    REMARK        VARCHAR(200)          DEFAULT '' COMMENT '备注',
    UPDATE_TIME   TIMESTAMP    NOT NULL DEFAULT NOW() COMMENT '更新时间',
    ENABLE_FILTER TINYINT(1)   NOT NULL DEFAULT 1 COMMENT '0: 不启用关键字过滤， 1: 启用',
    FILTER_TYPE   VARCHAR(5)   NOT NULL DEFAULT 'OR' COMMENT '关键字过滤类型，OR: 或，匹配任一关键字， AND: 与，匹配所有关键字',
    ENABLE        TINYINT(1)   NOT NULL DEFAULT 1 COMMENT '0: 不启用， 1: 启用',
    PRIMARY KEY (ID)
);
