-- DROP TABLE IF EXISTS T_ALARM_CONFIG;

CREATE TABLE IF NOT EXISTS T_ALARM_CONFIG
(
    ID          IDENTITY     NOT NULL COMMENT '主键ID',
    URL         VARCHAR(200) NOT NULL DEFAULT '' COMMENT '钉钉告警的url',
    SECRET      VARCHAR(100)          DEFAULT '' COMMENT '钉钉机器人加签',
    KEYS        VARCHAR(200) NOT NULL DEFAULT '' COMMENT '告警关键字',
    REMARK      VARCHAR(200)          DEFAULT '' COMMENT '备注',
    UPDATE_TIME TIMESTAMP    NOT NULL DEFAULT NOW() COMMENT '更新时间',
    PRIMARY KEY (ID)
);
